routes/web.php
<?php

use App\Http\Controllers\User\BillingController;
use App\Http\Controllers\User\CheckoutController;
use App\Http\Controllers\User\PaymentMethodController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use App\Http\Controllers\User\TipsController as TipsControllerUser;
use App\Http\Controllers\Poster\TipsController as TipsControllerPoster;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

require __DIR__ . '/auth.php';

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::middleware(['auth', 'verified'])->group(function () {

    Route::get('billing', [BillingController::class, 'index'])->name('billing');
    Route::get('checkout/{price_id}', [CheckoutController::class, 'checkout'])->name('checkout');
    Route::post('checkout', [CheckoutController::class, 'processCheckout'])->name('checkout.process');
    Route::get('cancel', [BillingController::class, 'cancel'])->name('cancel');
    Route::get('resume', [BillingController::class, 'resume'])->name('resume');
    Route::get('payment-methods/default/{methodId}', [PaymentMethodController::class, 'markDefault'])->name('payment-methods.markDefault');
    Route::resource('payment-methods', PaymentMethodController::class);
    Route::get('invoices/download{invoiceId}', [BillingController::class, 'downloadInvoice'])->name('invoices.download');
    Route::get('tips', [TipsControllerUser::class, 'index'])->name('tips.index');


    Route::group(
        [
            'prefix' => 'poster',
            'middleware' => 'is_poster',
            'as' => 'poster.',
        ],
        function () {
            Route::post('tips', [TipsControllerPoster::class, 'store'])->name('tips.store');
        }
    );
});


/* STRIPE WEBHOOKS*/
Route::stripeWebhooks('stripe-webhook');

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Cashier\Billable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable, Billable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'trial_ends_at',
        'company_name',
        'address_line_1',
        'address_line_2',
        'country_id',
        'city',
        'zipcode',

    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    
}

app/Http/Controllers/User/BillingController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Payment;
use Illuminate\Support\Facades\Auth;
use App\Models\Price;
use App\Http\Controllers\Controller;


class BillingController extends Controller
{
    public function index()
    {
        $prices = Price::all();

        $currentPrice = Auth::user()->subscription('default') ?? NULL;


        $paymentMethods = NULL;
        $defaultPaymentMethod = NULL;
        if (!is_null($currentPrice)) {
            $paymentMethods = Auth::user()->paymentMethods();
            $defaultPaymentMethod = Auth::user()->defaultPaymentMethod();
        }


        $payments = Payment::where('user_id', Auth::id())->latest()->get();
        return view('user.billing.index', compact(
            'prices',
            'currentPrice',
            'paymentMethods',
            'defaultPaymentMethod',
            'payments'
        ));
    }

    public function cancel()
    {
        Auth::user()->subscription('default')->cancel();
        return redirect()->route('billing');
    }

    public function resume()
    {
        Auth::user()->subscription('default')->resume();
        return redirect()->route('billing');
    }

    public function downloadInvoice($paymentId)
    {
        $payment = Payment::where('user_id', Auth::id())->where('id', $paymentId)->firstOrFail();
        $filename = storage_path('app/invoices/' . $payment->id . '.pdf');
        if (!file_exists($filename)) {
            abort(404);
        }
        return response()->download($filename);
    }
}

app/Http/Controllers/User/CheckoutController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Country;
use Illuminate\Support\Facades\Auth;
use App\Models\Price;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CheckoutController extends Controller
{
    public function checkout($price_id)
    {
        $price = Price::findOrFail($price_id);
        $countries = Country::all();
        $currentPlan = Auth::user()->subscription('default');
        $currentPrice = $currentPlan->stripe_plan ?? NULL;

        if (!is_null($currentPrice) && ($currentPrice != $price->stripe_price_id || $currentPlan->stripe_status != 'active')) {
            try {
                Auth::user()->subscription('default')->swapAndInvoice($price->stripe_price_id);
                return redirect()->route('billing');
            } catch (\Exception $e) {
                return redirect()->back()->withError($e->getMessage());
            }
        }

        $intent = Auth::user()->createSetupIntent();
        return view('user.billing.checkout', compact('price', 'intent', 'countries'));
    }

    public function processCheckout(Request $request)
    {
        $price = Price::findOrFail($request->input('billing_plan_id'));

        try {
            Auth::user()->newSubscription('default', $price->stripe_price_id)
                ->create($request->input('payment-method'));

            Auth::user()->update([
                //'trial_ends_at' => NULL,
                'company_name' => $request->input('company_name'),
                'address_line_1' => $request->input('address_line_1'),
                'address_line_2' => $request->input('address_line_2'),
                'country_id' => $request->input('country_id'),
                'city' => $request->input('city'),
                'zipcode' => $request->input('zipcode'),

            ]);

            return redirect()->route('billing')->withMessage('Subscribed successfully');
        } catch (\Exception $e) {
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

app/Http/Controllers/User/PaymentMethodController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PaymentMethodController extends Controller
{


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $intent = Auth::user()->createSetupIntent();
        return view('user.payment-methods.create', compact('intent'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            Auth::user()->addPaymentMethod($request->input('payment-method'));
            if ($request->input('default') == 1) {
                Auth::user()->updateDefaultPaymentMethod($request->input('payment-method'));
            }
        } catch (\Exception $e) {
            return redirect()->back()->withError($e->getMessage());
        }

        return redirect()->route('billing')->withMessage('Payment method added successfuly');
    }


    public function markDefault(Request $request, $paymentMethod)
    {
        try {
            Auth::user()->updateDefaultPaymentMethod($paymentMethod);
        } catch (\Exception $e) {
            return redirect()->back()->withError($e->getMessage());
        }

        return redirect()->route('billing')->withMessage('Payment method updated successfuly');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/TipsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Tips;
use Illuminate\Http\Request;

class TipsController extends Controller
{
    public function index(Request $request)
    {

        $this->authorize('tips');
        $tips = Tips::all();
        if ($request->is('api/*')) {
            return $tips;
        } else {
            return view('user.tips.index', compact('tips'));
        }
    }
}

resources/views/user/payment-methods/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Add payment method
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            @if (session('error'))
                            <div class="alert alert-danger"> {{ session('error') }}</div>
                            @endif
                            <form action="{{ route('payment-methods.store') }}" method="POST" id="checkout-form">
                                @csrf
                                <input type="hidden" name="payment-method" id="payment-method" value="">

                                <input id="card-holder-name" class="form-control" type="text" placeholder="Card holder name">

                                <!-- Stripe Elements Placeholder -->
                                <div id="card-element"></div>
                                <br>
                                <input type="checkbox" name="default" value="1" /> Mark as Default Method
                                <br><br>
                                <button id="card-button" class="btn btn-success mt-2">
                                    Add Method
                                </button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection



@section('scripts')
<script>
    $(document).ready(function() {

        let stripe = Stripe("{{ config('services.stripe.publishable_key') }}", {
            locale: 'us'
        });

        let elements = stripe.elements()
        let style = {
            base: {
                color: '#32325d',
                fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                fontSmoothing: 'antialiased',
                fontSize: '16px',
                '::placeholder': {
                    color: '#aab7c4'
                }
            },
            invalid: {
                color: '#fa755a',
                iconColor: '#fa755a'
            }
        }


        let card = elements.create('card', {
            style: style
        })

        card.mount('#card-element')




        let paymentMethod = null
        $('#checkout-form').on('submit', function(e) {
            if (paymentMethod) {
                return true
            }
            stripe.confirmCardSetup(
                "{{ $intent->client_secret }}", {
                    payment_method: {
                        card: card,
                        billing_details: {
                            name: $('#card-holder-name').val()
                        }
                    }
                }
            ).then(function(result) {
                if (result.error) {
                    console.log(result)
                    alert('error')
                } else {
                    paymentMethod = result.setupIntent.payment_method
                    $('#payment-method').val(paymentMethod)
                    $('#checkout-form').submit()
                }
            })
            return false
        })
    });
</script>
@endsection

@section('styles')
<style>
    .StripeElement {
        box-sizing: border-box;
        height: 40px;
        padding: 10px 12px;
        border: 1px solid transparent;
        border-radius: 4px;
        background-color: white;
        box-shadow: 0 1px 3px 0 #e6ebf1;
        -webkit-transition: box-shadow 150ms ease;
        transition: box-shadow 150ms ease;
    }

    .StripeElement--focus {
        box-shadow: 0 1px 3px 0 #cfd7df;
    }

    .StripeElement--invalid {
        border-color: #fa755a;
    }

    .StripeElement--webkit-autofill {
        background-color: #fefde5 !important;
    }
</style>
@endsection